"""initial tables

Revision ID: 64151e00c428
Revises: 
Create Date: 2026-05-23 20:19:34.262066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64151e00c428'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('water_quality_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('sample_date', sa.Date(), nullable=False),
    sa.Column('enterococci_per_100ml', sa.Integer(), nullable=False),
    sa.Column('quality_code', sa.String(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'sample_date', name='uq_sample_site_date')
    )
    op.create_index(op.f('ix_water_quality_samples_id'), 'water_quality_samples', ['id'], unique=False)
    op.create_table('weather_daily_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('precipitation_inches', sa.Float(), nullable=True),
    sa.Column('avg_temp_f', sa.Float(), nullable=True),
    sa.Column('min_temp_f', sa.Float(), nullable=True),
    sa.Column('max_temp_f', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'weather_date', name='uq_weather_site_date')
    )
    op.create_index(op.f('ix_weather_daily_record_id'), 'weather_daily_record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_daily_record_id'), table_name='weather_daily_record')
    op.drop_table('weather_daily_record')
    op.drop_index(op.f('ix_water_quality_samples_id'), table_name='water_quality_samples')
    op.drop_table('water_quality_samples')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
