"""remove site_id from weather record

Revision ID: 970d05033539
Revises: 64151e00c428
Create Date: 2026-05-25 10:32:41.479744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970d05033539'
down_revision: Union[str, Sequence[str], None] = '64151e00c428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_weather_site_date'), 'weather_daily_record', type_='unique')
    op.create_unique_constraint('uq_weather_site_date', 'weather_daily_record', ['weather_date'])
    op.drop_constraint(op.f('weather_daily_record_site_id_fkey'), 'weather_daily_record', type_='foreignkey')
    op.drop_column('weather_daily_record', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_daily_record', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('weather_daily_record_site_id_fkey'), 'weather_daily_record', 'sites', ['site_id'], ['id'])
    op.drop_constraint('uq_weather_site_date', 'weather_daily_record', type_='unique')
    op.create_unique_constraint(op.f('uq_weather_site_date'), 'weather_daily_record', ['site_id', 'weather_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
